#some_file: other_file
#	echo "This will always run, and runs second"
#	touch some_file

#other_file:
#	echo "This will always run, and runs first"

some_file: 
	touch some_file

clean:
	rm -f some_file